// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdpg4vWPmbKsbuXvP6r2xDInhOXXfWjEw',
    appId: '1:52793499562:web:d1817e122a24d0220ed5d3',
    messagingSenderId: '52793499562',
    projectId: 'fir-server-3c42f',
    authDomain: 'fir-server-3c42f.firebaseapp.com',
    databaseURL: 'https://fir-server-3c42f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-server-3c42f.appspot.com',
    measurementId: 'G-NY7WHLE9JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO37VHPLKBZdeKADkm4oQ5lO0yIGvvyGU',
    appId: '1:52793499562:android:baf09365a20094b30ed5d3',
    messagingSenderId: '52793499562',
    projectId: 'fir-server-3c42f',
    databaseURL: 'https://fir-server-3c42f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-server-3c42f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdITu-Bb3-Wdq_n3fDbRXCLCGd1Ck6JjQ',
    appId: '1:52793499562:ios:fc18da514f9caf6d0ed5d3',
    messagingSenderId: '52793499562',
    projectId: 'fir-server-3c42f',
    databaseURL: 'https://fir-server-3c42f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-server-3c42f.appspot.com',
    iosBundleId: 'com.example.contactManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdITu-Bb3-Wdq_n3fDbRXCLCGd1Ck6JjQ',
    appId: '1:52793499562:ios:9feff9c4ef16d7f50ed5d3',
    messagingSenderId: '52793499562',
    projectId: 'fir-server-3c42f',
    databaseURL: 'https://fir-server-3c42f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-server-3c42f.appspot.com',
    iosBundleId: 'com.example.contactManager.RunnerTests',
  );
}
